// client/src/components/MessageList.tsx
import { CheckIcon, CopyIcon, RefreshCwIcon } from 'lucide-react'

import { MarkdownMessage } from '#components/MarkdownMessage'
import { ReasoningDisclosure } from '#components/ReasoningDisclosure'
import { Button } from '#components/ui/button'
import { CHAT_CONTENT_COLUMN_CLASS } from '#lib/chatLayout'
import { cn } from '#lib/utils'
import type { ChatMessage, ToolActivity } from '#types/chat'

type MessageListProps = {
  copiedMessageId: string | null
  isResponding: boolean
  messages: ChatMessage[]
  onCopyMessage: (message: ChatMessage) => void
  onRetryMessage: (index: number) => void
}

function getToolActivityLabel(activity: ToolActivity) {
  if (activity.status === 'running') return '执行中'
  if (activity.status === 'stopped') return activity.summary || '已停止'
  return activity.summary || (activity.status === 'success' ? '执行完成' : '执行失败')
}

export function MessageList({
  copiedMessageId,
  isResponding,
  messages,
  onCopyMessage,
  onRetryMessage,
}: MessageListProps) {
  return (
    <div className={cn('message-list flex flex-col gap-[22px] max-[820px]:gap-1.5', CHAT_CONTENT_COLUMN_CLASS)}>
      {messages.map((message, index) => {
        const isUser = message.role === 'user'
        const hasReasoning = Boolean(message.reasoningText)

        return (
          <article
            className={cn(
              'message-row group items-start py-[9px] pb-[13px]',
              message.role,
              message.status === 'pending' && 'pending items-center',
              isUser
                ? 'flex justify-end pt-2 pb-3.5'
                : 'grid grid-cols-[minmax(0,1fr)]',
            )}
            key={message.id}
          >
            <div
              className={cn(
                'message-content flex min-w-0 flex-col gap-[7px]',
                isUser
                  ? 'max-w-[min(72%,520px)] items-end max-[820px]:max-w-[88%]'
                  : 'max-w-[932px] dark:max-w-[884px] max-[820px]:max-w-full',
              )}
            >
            {message.role === 'assistant' ? <ReasoningDisclosure {...message} /> : null}

            {message.role === 'assistant' && message.toolActivities?.length ? (
              <div aria-label="工具执行状态" className="tool-activity-list flex flex-col gap-[5px] text-xs text-[var(--text-secondary)]">
                {message.toolActivities.map((activity) => (
                  <div className={`tool-activity ${activity.status} grid grid-cols-[7px_auto_minmax(0,1fr)] items-center gap-[7px]`} key={activity.id}>
                    <span
                      aria-hidden="true"
                      className={cn(
                        'tool-activity-indicator size-1.5 rounded-full bg-[var(--text-tertiary)]',
                        activity.status === 'running' && 'animate-pulse',
                        activity.status === 'success' && 'bg-[var(--success)]',
                        activity.status === 'error' && 'bg-[var(--danger)]',
                      )}
                    />
                    <strong>{activity.name}</strong>
                    <span>{getToolActivityLabel(activity)}</span>
                  </div>
                ))}
              </div>
            ) : null}

            {message.status === 'pending' ? (
              <div className="message-text thinking-text inline-flex w-fit animate-pulse text-[13px] text-[var(--text-secondary)]">Thinking...</div>
            ) : message.status === 'error' && !message.text ? (
              <div className="message-text error-text text-[var(--danger)]">{message.error || '响应失败，请重试'}</div>
            ) : message.role === 'user' ? (
              <div className="message-text [overflow-wrap:anywhere] rounded-[12px_12px_3px_12px] bg-[var(--user-message-bg)] px-6 py-3 text-sm leading-[1.55] whitespace-pre-wrap text-[var(--user-message-text)] max-[820px]:px-[13px] max-[820px]:py-[9px]">
                {message.text}
              </div>
            ) : message.text ? (
              <MarkdownMessage
                className={cn(
                  'message-text [overflow-wrap:anywhere] text-sm leading-[1.65] font-normal whitespace-pre-wrap text-[var(--text-primary)]',
                  hasReasoning && 'mt-1.5',
                )}
                content={message.text}
                streaming={message.status === 'streaming'}
              />
            ) : null}

            {message.status === 'error' && message.text ? (
              <div className="message-status-text error-text text-xs font-medium text-[var(--danger)]">
                {message.error || '响应失败，请重试'}
              </div>
            ) : null}
            {message.status === 'stopped' ? (
              <div className="message-status-text text-xs font-medium text-[var(--text-secondary)]">已停止生成</div>
            ) : null}

            {message.role === 'assistant' ? (
              <div className="message-actions flex items-center gap-0.5 opacity-100 transition-opacity">
                {message.text && message.status !== 'pending' && message.status !== 'streaming' ? (
                  <Button
                    aria-label={copiedMessageId === message.id ? '已复制' : '复制回答'}
                    className="message-action-btn min-h-7 gap-[5px] rounded-md px-[7px] text-[11px] text-[var(--text-tertiary)] hover:bg-[var(--surface-muted)] hover:text-[var(--text-primary)]"
                    onClick={() => onCopyMessage(message)}
                    size="xs"
                    type="button"
                    variant="ghost"
                  >
                    {copiedMessageId === message.id ? (
                      <CheckIcon aria-hidden="true" size={15} />
                    ) : (
                      <CopyIcon aria-hidden="true" size={15} />
                    )}
                    <span>{copiedMessageId === message.id ? '已复制' : '复制'}</span>
                  </Button>
                ) : null}
                {message.status === 'error' ? (
                  <Button
                    className="message-action-btn min-h-7 gap-[5px] rounded-md px-[7px] text-[11px] text-[var(--text-tertiary)] hover:bg-[var(--surface-muted)] hover:text-[var(--text-primary)]"
                    disabled={isResponding}
                    onClick={() => onRetryMessage(index)}
                    size="xs"
                    type="button"
                    variant="ghost"
                  >
                    <RefreshCwIcon aria-hidden="true" size={15} />
                    <span>重试</span>
                  </Button>
                ) : null}
              </div>
            ) : null}
            </div>
          </article>
        )
      })}
    </div>
  )
}

// client/src/components/MessageList.vue
<template>
  <div class="message-list">
    <article
      v-for="(msg, index) in messages"
      :key="msg.id"
      :class="['message-row', msg.role, { pending: msg.status === 'pending' }]"
    >
      <div v-if="msg.role === 'assistant'" class="message-avatar">AI</div>
      <div class="message-content">
        <details
          v-if="msg.role === 'assistant' && msg.reasoningText"
          class="reasoning-panel"
          :open="msg.status === 'streaming'"
        >
          <summary class="reasoning-summary">
            {{ getReasoningLabel(msg) }}
          </summary>
          <div class="reasoning-content">
            <div class="reasoning-content-body">{{ msg.reasoningText.trim() }}</div>
          </div>
        </details>
        <div
          v-if="msg.role === 'assistant' && msg.toolActivities?.length"
          class="tool-activity-list"
          aria-label="工具执行状态"
        >
          <div
            v-for="activity in msg.toolActivities"
            :key="activity.id"
            :class="['tool-activity', activity.status]"
          >
            <span class="tool-activity-indicator" aria-hidden="true"></span>
            <strong>{{ activity.name }}</strong>
            <span>{{ getToolActivityLabel(activity) }}</span>
          </div>
        </div>
        <div v-if="msg.status === 'pending'" class="message-text thinking-text">Thinking...</div>
        <div v-else-if="msg.status === 'error' && !msg.text" class="message-text error-text">
          {{ msg.error || '响应失败，请重试' }}
        </div>
        <div v-else-if="msg.role === 'user'" class="message-text">{{ msg.text }}</div>
        <MarkdownMessage
          v-else-if="msg.text"
          class="message-text"
          :content="msg.text"
          :streaming="msg.status === 'streaming'"
        />
        <div v-if="msg.status === 'error' && msg.text" class="message-status-text error-text">
          {{ msg.error || '响应失败，请重试' }}
        </div>
        <div v-if="msg.status === 'stopped'" class="message-status-text">已停止生成</div>
        <div v-if="msg.role === 'assistant'" class="message-actions">
          <button
            v-if="msg.text && msg.status !== 'pending' && msg.status !== 'streaming'"
            class="message-action-btn"
            type="button"
            @click="$emit('copyMessage', msg)"
          >
            {{ copiedMessageId === msg.id ? '已复制' : '复制' }}
          </button>
          <button
            v-if="msg.status === 'error'"
            class="message-action-btn"
            type="button"
            :disabled="isResponding"
            @click="$emit('retryMessage', index)"
          >
            重试
          </button>
        </div>
      </div>
    </article>
  </div>
</template>

<script setup lang="ts">
import MarkdownMessage from './MarkdownMessage.vue'
import type { ChatMessage, ToolActivity } from '@/types/chat'

defineProps<{
  copiedMessageId: string | null
  isResponding: boolean
  messages: ChatMessage[]
}>()

defineEmits<{
  copyMessage: [message: ChatMessage]
  retryMessage: [index: number]
}>()

function getReasoningLabel(message: ChatMessage) {
  if (message.status === 'streaming' && !message.text) {
    return 'Thinking...'
  }

  return 'Thoughts'
}

function getToolActivityLabel(activity: ToolActivity) {
  if (activity.status === 'running') return '执行中'
  if (activity.status === 'stopped') return activity.summary || '已停止'
  return activity.summary || (activity.status === 'success' ? '执行完成' : '执行失败')
}
</script>
